config/routes.rb
Rails.application.routes.draw do
  namespace :api, defaults: { format: :json } do
    post '/authenticate_user', to: 'authentication#authenticate_user'
    resources :transactions, only: :create
  end

  devise_for :users
  root to: 'users#index'
  resources :users do
    resources :transactions, only: :index
  end
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  has_many :transactions

  enum role: %i[admin merchant]
  enum status: %i[active inactive]

  scope :admins, -> { where(role: :admin) }
  scope :merchants, -> { where(role: :merchant) }

  # set default role to merchant as soon as we initialize the User
  after_initialize do
    self.role ||= :merchant if new_record?
  end

  before_save do
    self.total_transaction_sum = transactions.charged.approved.sum(:amount) if merchant?
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :set_user, only: %i[show edit update destroy]

  # GET /users
  # GET /users.json
  def index
    @users = User.merchants
  end

  # GET /users/1
  # GET /users/1.json
  def show; end

  # GET /users/new
  def new
    @user = User.new
  end

  # GET /users/1/edit
  def edit; end

  # POST /users
  # POST /users.json
  def create
    @user = User.new(user_params)

    respond_to do |format|
      if @user.save
        format.html { redirect_to @user, notice: 'User was successfully created.' }
        format.json { render :show, status: :created, location: @user }
      else
        format.html { render :new }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /users/1
  # PATCH/PUT /users/1.json
  def update
    respond_to do |format|
      if @user.update(user_params)
        format.html { redirect_to @user, notice: 'User was successfully updated.' }
        format.json { render :show, status: :ok, location: @user }
      else
        format.html { render :edit }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /users/1
  # DELETE /users/1.json
  def destroy
    @user.destroy
    respond_to do |format|
      format.html { redirect_to users_url, notice: 'User was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private

  # Use callbacks to share common setup or constraints between actions.
  def set_user
    @user = User.find(params[:id])
  end

  # Only allow a list of trusted parameters through.
  def user_params
    params.require(:user).permit(:name, :description, :email, :status,
                                 :total_transaction_sum)
  end
end

app/views/users/_form.html.slim
= form_for @user do |f|
  - if @user.errors.any?
    #error_explanation
      h2 = "#{pluralize(@user.errors.count, "error")} prohibited this user from being saved:"
      ul
        - @user.errors.full_messages.each do |message|
          li = message

  .form-row
    .col-md-4.mb-3
      = f.label :name
      = f.text_field :name, class: 'form-control', placeholder: 'Name'

  .form-row
    .col-md-4.mb-3
      = f.label :email
      = f.email_field :email, class: 'form-control', placeholder: 'Email'

  .form-row
    .col-md-4.mb-3
      = f.label :description
      = f.text_area :description, class: 'form-control', placeholder: 'Description'

  = f.submit 'Submit', class: 'btn btn-info'

app/views/users/_user.html.slim
tr
  td = user.name
  td = user.email
  td = user.description
  td = user.status
  td = user.total_transaction_sum
  td = link_to 'Show', user
  td = link_to 'Transactions', user_transactions_path(user)
  td = link_to 'Edit', edit_user_path(user)
  td = link_to 'Destroy', user, data: { confirm: 'Are you sure?' }, method: :delete

app/views/users/edit.html.slim
h1 Editing user

== render 'form'

br
=> link_to 'Show', @user, class: 'btn btn-info'

=< link_to 'Back', users_path, class: 'btn btn-info'

app/views/users/index.html.slim
h1 Users

table.table
  thead
    tr
      th Name
      th Email
      th Description
      th Status
      th Total Transaction Sum
      th colspan="4"

  tbody
    = render partial: 'user', collection: @users

br

= link_to 'New User', new_user_path, class: 'btn btn-info'

app/views/users/new.html.slim
h1 New user

== render 'form'

br
= link_to 'Back', users_path, class: 'btn btn-info'

app/views/users/show.html.slim
p#notice = notice

p
  strong Name:
  = @user.name
p
  strong Email:
  = @user.email
p
  strong Description:
  = @user.description
p
  strong Status:
  = @user.status
p
  strong Total Transaction Sum:
  = @user.total_transaction_sum

=> link_to 'Edit', edit_user_path(@user), class: 'btn btn-info'

=< link_to 'Back', users_path, class: 'btn btn-info'